name: image-url-database
dependencies:
- certifi=2016.2.28=py36_0
- click=6.7=py36_0
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - faunadb==2.7.0
  - future==0.17.1
  - imagehash==4.0
  - iso8601==0.1.12
  - numpy==1.16.4
  - pywavelets==1.0.3
  - scipy==1.3.0
  - six==1.12.0

